import {
  Search,
  Cancel,
  ViewColumn,
  FilterList,
  Visibility,
  VisibilityOff,
  HomeOutlined,
  Menu,
  Close,
  AddBoxOutlined,
  IndeterminateCheckBoxOutlined,
  ArrowDropDown,
  WarningOutlined,
  ErrorOutline,
  CheckCircleOutlineOutlined,
} from '@material-ui/icons'

export default {
  col_menu: ViewColumn,
  eye_off: VisibilityOff,
  eye_on: Visibility,
  filter_list: FilterList,
  home: HomeOutlined,
  search: Search,
  search_clear: Cancel,
  menu: Menu,
  close: Close,
  plus: AddBoxOutlined,
  minus: IndeterminateCheckBoxOutlined,
  dropdown: ArrowDropDown,
  warning: WarningOutlined,
  error: ErrorOutline,
  success: CheckCircleOutlineOutlined,
}
